version: "3"
services:
  user-service:
    container_name:  user-service
    image:  lalsimte/user-service
    build: .
    restart: always
    environment:
      NODE_ENV : production
      DB_HOST : mongo-users-db
      DB_PORT : 27018
      DB_NAME : users
    links:
      - mongo-users-db
    ports: 
      - 4000:4000
    

  mongo-users-db:
    container_name: mongo-users-db
    image: mongo:latest
    restart: always
    volumes:
      - mongo-users-db:/data/db
    command: mongod --port 27018
    ports:
      - "27018:27018"

volumes: 
  mongo-users-db : {}