apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: livenessprobe
spec:
  containers:
    - name: livenessprobe
      image: lalsimte/user-service
      args:
        - /bin/sh
        - -c
        - touch /tmp/healthy; sleep 30; rm -f /tmp/healthy; sleep 600
      livenessProbe:
        exec:
          command:
            - cat
            - /tmp/healthy
        initialDelaySeconds: 5
        periodSeconds: 5
