apiVersion: v1
kind: Service
metadata:
  namespace: users
  name: user-service-mongosvc
  labels:
    name: user-service-mongo
spec:
  ports:
    - port: 27017
      targetPort: 27017
  clusterIP: None
  selector:
    app: user-service-mongo
