apiVersion: v1
kind: Service
metadata:
  namespace: users
  name: user-service-mongosvc
  labels:
    name: user-service-mongo
spec:
  ports:
    - port: 27017
      targetPort: 27017
  clusterIP: None
  selector:
    app: user-service-mongo

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: users
  name: user-service-mongodb
spec:
  selector:
    matchLabels:
      app: user-service-mongo
  serviceName: user-service-mongosvc
  replicas: 3
  template:
    metadata:
      labels:
        app: user-service-mongo
    spec:
      containers:
        - name: user-service-mongo
          image: mongo
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: user-service-mongodb
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        namespace: users
        name: user-service-mongodb
      spec:
        accessModes: ["ReadWriteMany"]
        storageClassName: hostpath
        resources:
          requests:
            storage: 500Mi
