apiVersion: v1
kind: Service
metadata:
  namespace: users
  name: order-service
  labels:
    name: order-service
    app: order-service
spec:
  #  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  #     nodePort: 32000
  selector:
    app: order-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: users
  name: order-service
  labels:
    app: order-service
    name: order-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        name: order-service
        app: order-service
    spec:
      containers:
        - image: lalsimte/order-service
          name: foodapp-orders
          ports:
            - containerPort: 80
          env:
            - name: NODE_ENV
              value: "development"
            - name: PORT
              value: "80"
            - name: DB_PORT
              value: "27017"
            - name: DB_HOST
              value: "order-service-mongosvc"
