---
apiVersion: v1
kind: Namespace
metadata:
  name: users
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: users
  name: user-service
  labels:
    app: user-service
    name: user-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        name: user-service
        app: user-service
    spec:
      containers:
        - image: lalsimte/user-service
          name: foodapp-users
          ports:
            - containerPort: 80

          # Liveness test configuration
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10

          # Readiness test configuration
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          env:
            - name: NODE_ENV
              value: "development"
            - name: PORT
              value: "80"
            - name: DB_PORT
              value: "27017"
            - name: DB_HOST
              value: "user-service-mongosvc"
